version: "3.8"
services:

  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_CUSTOM_LDIF_DIR=/ldifs
    volumes:
      - 'openldap_data:/bitnami/openldap'
      - './src/main/resources/:/ldifs'

volumes:
  openldap_data:
    name: openldap_data
    driver: local